name: CI/CD Pipeline for ML Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Linting job
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pylint
        run: |
          pylint --max-line-length=120 --disable=C0114,C0115,C0116 *.py

  # Testing job
  test:
    runs-on: ubuntu-latest
    needs: lint  # Ensure linting passes before running tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with Pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q

  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure tests pass before deploying
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy Model
        run: |
          # Example deployment command (modify according to your requirements)
          echo "Deploying the model..."
          # (Here you can add your deployment logic)
          # For example, pushing the model to a cloud storage, or using another deployment service.
