name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest scikit-learn

      # Step 4: Run pylint for linting
      - name: Run pylint
        run: pylint *.py

      # Step 5: Run pytest for testing
      - name: Run pytest
        run: pytest test_train.py

      # Step 6: Deployment step (placeholder)
      # Replace this step with your actual deployment logic
      - name: Deploy model
        run: echo "Deployment step placeholder. Add your deployment logic here."
